### ISSUE TITLE
Mobile design

### ISSUE THREAD

**Issue by mnieber** [fdrtd/website#2]
Hi Hendrik, it's Maarten :-). I've taken a short look at the source code. First, I have to say that:

- I'm not an expert on CSS, but I've developed a few practices that work well for me
- CSS is not an easy topic either. There are different approaches, and often it's not clear which is the best one

Regarding positioning the footer, I (way too late) found out that these CSS tricks webpages are very useful. For example, I found this: https://css-tricks.com/couple-takes-sticky-footer/. This site is also good (it solves various frequently occurring design challenges): https://csslayout.io/

AFAIK there is no general strategy to make a design work well on mobile, except for the rather obvious approach (that is still worth mentioning, I think, but I apologize if this is too basic to be useful): 

- look at a screen on the smallest width that you support
- fix the design
- slowly make the screen wider until you notice that it starts to look bad (this is where you need a breakpoint)
- add the break-point and related CSS rules so that the screen looks good again
- repeat

Notice that this approach does not assume fixed breakpoints! But you can use it in a similar way if you do have fixed breakpoints.
In my projects so far I've used fixed breakpoints, and I've found that TailwindCSS is a great help in making the design responsive. Since you are using gatsby, these would be the steps for adding Tailwind: https://www.gatsbyjs.com/docs/how-to/styling/tailwind-css/. As a short example, imagine that on small screens you want a div to take half the parent size, and on larger screens a third. With Tailwind this would be:

[div className="sm:w-1/2 lg:w-1/3"]Hello[/div]

In general, any style rule can be prefixed with the screen width at which it applies. If you have a specific case in mind, I could try to tackle it using Tailwind so you get an impression, let me know :-).

**Comment by Ballhausen** [comment]
Hi Maarten, thank you very much.
We put breakpoints conservatively at 800 and 1200 px.
More importantly, we did and we will simplify the layout, no unnecessary images, no unconditional multi column layout.
Looks reasonably okay on a smartphone now, so I will close this issue for the time being.
